# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "thunderbolt" "nvme" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];
  boot.supportedFilesystems = ["ntfs"];

  # Ideally make boot sequence less verbos. Likely only applies to stage 2 vs. stage 1. See: http://github.com/NixOS/nixpkgs/issues/32555
  # Disable i915 PSR (Panel Self Refresh) to avoid screen freezing issue: https://chatgpt.com/c/68f6e22a-f564-8324-b3b3-812c4a9bbfce
  boot.kernelParams = ["quiet" "udev.log_level=3" "i915.enable_psr=0"];
  boot.consoleLogLevel = 0;
  boot.initrd.verbose = false;

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/d1de93b0-5509-4c44-b374-76055ff05aef";
    fsType = "ext4";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/f0727750-31b7-4645-bbf8-f8ef64cfe8bf";
    fsType = "ext4";
  };

  fileSystems."/efi" = {
    device = "/dev/disk/by-uuid/AC92-5873";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/B975-1010";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [
    {
      device = "/dev/disk/by-uuid/70fb9644-66fe-4d1b-9fd8-0c583b6ea1bd";
    }
  ];

  # Enables zram which will compress in memory before falling back to swap partition.
  # 50% seemed a normal amount for laptops use, but can lower to 25% if too much.
  zramSwap = {
    enable = true;
    memoryPercent = 50;
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s13f0u3u6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
